name: Jest Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable

    - name: Setup ChromeDriver
      uses: nanasess/setup-chromedriver@v2

    - name: Install dependencies
      run: npm ci

    - name: Setup Database
      run: |
        npx prisma generate
        npx prisma db push
        npx prisma db seed

    - name: Run tests
      run: |
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
        npm test
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        SELENIUM_BROWSER: chrome
        SELENIUM_HEADLESS: true 